# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               My Brain
tagline:             'A collection of things'
description:         '  Thanks for all the fish '
url:                 http://mikebeaulieu.github.io
baseurl:             ''
#paginate:            5
gems: [jekyll-paginate]
paginate: 2

# About/contact
author:
  name:              Mike Beaulieu
  url:               
  email:             mike.beaulieu@firmafx.com

# Custom vars
version:             1.0.0

collections:
  statusupdates:
    output: true
  about:
    output: true
